# Dependencies
markdown:         github
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Hello Wolrd
tagline:          'Blog'
description:      'Have a nice day!😄'
url:              https://choijunwoo.github.io
baseurl:          /

author:
  name:           'Junwoo Choi'
  url:            https://www.linkedin.com/in/choijunwoo

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/choijunwoo/choijunwoo.github.io/
